### PR TITLE
Transfer Funds Feature

### PR DESCRIPTION
**Pull request by jmanoj0905**

### CODE REVIEW

**Comment by Lohithsurya** [comment]
its not taking care when your amount is less than the amount you wanna transfer. Pls check that and im happy to give full points

**Comment by jmanoj0905** [comment]
Sure I will look into it

**Comment by jmanoj0905** [comment]
I have made my changes please look into it

**Comment by Lohithsurya** [comment]
!bounty 400

**Comment by Lohithsurya** [comment]
!bounty @Lohithsurya 400

**Comment by Lohithsurya** [comment]
!bounty @Lohithsurya 300

**Comment by bwaklog** [comment]
!bounty @Lohithsurya 300

**Comment by Lohithsurya** [comment]
!bounty 300

**Comment by Lohithsurya** [comment]
!bounty 399

**Comment by Lohithsurya** [comment]
!bounty 400

**Pull request merged**
